/* 
 * AutoRest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DestinationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DestinationsApiTests
    {
        private DestinationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DestinationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinationsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DestinationsApi
            //Assert.IsInstanceOfType(typeof(DestinationsApi), instance, "instance is a DestinationsApi");
        }

        /// <summary>
        /// Test ApiDestinationsGet
        /// </summary>
        [Test]
        public void ApiDestinationsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiDestinationsGet();
            //Assert.IsInstanceOf<List<Destination>> (response, "response is List<Destination>");
        }
        /// <summary>
        /// Test ApiDestinationsIdDelete
        /// </summary>
        [Test]
        public void ApiDestinationsIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiDestinationsIdDelete(id);
            
        }
        /// <summary>
        /// Test ApiDestinationsIdGet
        /// </summary>
        [Test]
        public void ApiDestinationsIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiDestinationsIdGet(id);
            //Assert.IsInstanceOf<Destination> (response, "response is Destination");
        }
        /// <summary>
        /// Test ApiDestinationsIdPut
        /// </summary>
        [Test]
        public void ApiDestinationsIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //Destination body = null;
            //instance.ApiDestinationsIdPut(id, body);
            
        }
        /// <summary>
        /// Test ApiDestinationsPost
        /// </summary>
        [Test]
        public void ApiDestinationsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Destination body = null;
            //instance.ApiDestinationsPost(body);
            
        }
    }

}
