openapi: 3.0.1
info:
  title: AutoRest
  version: v1
paths:
  /api/Destinations:
    get:
      tags:
        - Destinations
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
    post:
      tags:
        - Destinations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destination'
          text/json:
            schema:
              $ref: '#/components/schemas/Destination'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Destination'
      responses:
        '200':
          description: Success
  '/api/Destinations/{id}':
    get:
      tags:
        - Destinations
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Destination'
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
            text/json:
              schema:
                $ref: '#/components/schemas/Destination'
    put:
      tags:
        - Destinations
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destination'
          text/json:
            schema:
              $ref: '#/components/schemas/Destination'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Destination'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Destinations
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /WeatherForecast:
    get:
      tags:
        - WeatherForecast
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
components:
  schemas:
    Destination:
      type: object
      properties:
        id:
          type: integer
          format: int32
        cityName:
          type: string
          nullable: true
        airport:
          type: string
          nullable: true
      additionalProperties: false
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date-time
        temperatureC:
          type: integer
          format: int32
        temperatureF:
          type: integer
          format: int32
          readOnly: true
        summary:
          type: string
          nullable: true
      additionalProperties: false
